### ISSUE TITLE
FINEMAPinf resulting in more SNPs with PIP > 0.9 than regular FINEMAP?

### ISSUE THREAD

**Issue by gunns2** [FinucaneLab/fine-mapping-inf#11]
Hello,

I am running both SuSiE-inf and FINEMAP-inf in addition to regular SuSiE and FINEMAP and finding that FINEMAP-inf is resulting in far more variants with high PIP than the other methods. This is surprising given the results in the FINEMAPinf/SuSiEinf paper. Do you have any idea why this may be happening? SuSiE-inf seems to be behaving fine and there are no errors in the log files. 

I am also right now treating a binary trait as continuous. Could this be the issue?

thanks so much!

Sophie

**Comment by cuiran** [comment]
Hi Sophie,

Are you using in-sample LD or reference LD? I find FINEMAP-inf to be much more susceptible to LD mismatch than the other methods. There are other complications that comes with using reference panel LD. We didn't address this in the paper because both inf methods are developed for the use of single-cohort fine-mapping with in-sample LD. But I am aware that sometimes people use these methods with reference panel LD, and sometimes with meta-analyzed GWAS. I'd recommend caution in this case. If this is your use case, I recommend checking out the fine-mapping methods that are developed with this in mind, like [SLALOM](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9839193/) or [CARMA](https://www.nature.com/articles/s41588-023-01392-0).

**Comment by gunns2** [comment]
Hello,

Thank you so much for the prompt response! I think this is probably the issue. We were already planning on implementing SLALOM but I will check out CARMA.

Thanks again!
