### ISSUE TITLE
Tuning parameter L

### ISSUE THREAD

**Issue by harryyiheyang** [FinucaneLab/fine-mapping-inf#12]
Hi there,
Could you please check if there is an option to set different number of L (the default seems to be 10)?
Thank you

**Comment by cuiran** [comment]
Hi, the L is set by "--num-sparse-effects" in the python wrapper. The default is indeed 10.

**Comment by yu-zhang-oYo** [comment]
Hi, after using the default value of L=10, I got 2 credible sets, do I need to refit the model with L=2 (--num-sparse-effects 2) as the final results? Because these two setting lead to different results. I am not sure which result I should use. 

Besides, for the LD calculation, I use plink --r to calculate the LD matrix, is that suitable? Must I use LDstore to calculate it? 

My understanding of this fine-mapping-inf methods can be used for the summary statistics from mixed model of binary outcome. please correct me if it is not.

Thanks for any help.

**Comment by cuiran** [comment]
Hi, sorry for the late response. I'm aware that the results can be different when L is set differently, but when I investigated this, the results are not too different, especially when PIPs are higher. But I didn't investigate very thoroughly. SuSiE also has this issue. How different are your results when you set L differently? In the SuSiE paper they recommend you setting the L to be one more than the number of true causal variants. So if you think there are 2, set L=3.
